### ISSUE TITLE
Assignment Serving

### ISSUE THREAD

**Issue by Endoman123** [Endoman123/rucentral#4]
Create tab for displaying and submitting assignments.

## MILESTONES
- [ ] Create general assignment format
- [ ] Adapt general assignment format for Canvas
- [ ] Adapt general assignment format for Sakai
- [ ] Create UI for file submissions
- [ ] Create UI for text submission via WYSIWYG
