### ISSUE TITLE
Announcement Serving

### ISSUE THREAD

**Issue by Endoman123** [Endoman123/rucentral#5]
Create announcements tab for displaying all announcements.

## MILESTONES
- [ ] Create general announcements format
- [ ] Adapt Canvas announcements
- [ ] Adapt Sakai announcements
